repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
    rev: v0.2.2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.13.0
    hooks:
    - id: sourcery
      # The best way to use Sourcery in a pre-commit hook:
      # * review only changed lines:
      # * omit the summary
      args: [--diff=git diff HEAD, --no-summary]
